theme = "onedark_planccck"

[editor]
scrolloff = 1
true-color = true
line-number = "relative"
mouse = false
bufferline = "always"
auto-completion = false
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-type", "total-line-numbers", "file-encoding"]
center = ["file-name"]
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.soft-wrap]
enable = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
space = { w = ":write", W = ":write!", q = ":quit", Q = ":quit!", x = ":write-quit" }

[keys.insert]
j = { k = "normal_mode" }
