theme = "onedark_planccck"

[editor]
scrolloff = 0
true-color = true
line-number = "relative"
mouse = false
bufferline = "always"
auto-completion = false
auto-pairs = false

[editor.whitespace.render]
newline = "all"
nbsp = "all"

[editor.whitespace.characters]
nbsp = "⍽"
newline = "↲"

[editor.indent-guides]
render = true
character = "⫶" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
left = ["mode", "spinner", "file-type", "total-line-numbers", "file-encoding", "file-name"]
center = []
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics", "version-control"]

[editor.lsp]
auto-signature-help = false
display-messages = true

[editor.soft-wrap]
enable = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
space = { w = ":write", W = ":write!", q = ":quit", Q = ":quit!", x = ":write-quit" }
"C-e" = "scroll_down"
"C-y" = "scroll_up"
"C-w" = { c = "wclose" }
