[[language]]
name = "go"
language-servers = [ "gopls", "golangci-lint" ]

[language-server.gopls]
config = { gopls = { gofumpt = true } }

[language-server.golangci-lint]
command = "golangci-lint-langserver"
config = { command = ["golangci-lint", "run", "--enable-all", "--out-format", "json", "--issues-exit-code=1"] }

[[language]]
name = "toml"
auto-format = true
